In [1]:
import numpy as np

In [2]:
data1 = [6,7.5,8,0,1]
data1

[6, 7.5, 8, 0, 1]

In [3]:
# numpy를 이용하여 1차원 배열로 변형하기

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 배열의 크기 확인
arr1.shape

(5,)

In [5]:
# 2차원 List

data2 = [
    [1,2,3,4],
    [5,6,7,8]
]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
# numpy로 2차원 배열로 변형하기
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.shape

(2, 4)

In [8]:
# 0으로 구성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros([3, 5, 2]) # 3 => page(괄호 내 값 3개일경우 3차원)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
# 1로만 구성된 배열생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# 숫자 8로 구성된 3행 5열 배열 생성
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [16]:
# 범위가 있는 배열 생성
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr1.dtype

dtype('float64')

In [19]:
arr3 = np.array([1,2,3,4,5],dtype=np.int64)
arr3.dtype
arr3

array([1, 2, 3, 4, 5])

In [20]:
# data type을 변경
float_arr1 = arr3.astype(np.float64)
float_arr1.dtype

dtype('float64')

In [21]:
float_arr1

array([1., 2., 3., 4., 5.])

In [26]:
# 연산
arr1 = np.array([
    [1,2,3],
    [4,5,6]
],dtype=np.float64)

# arr1 = np.array((
#     [1,2,3],
#     [4,5,6]
# ))

arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
arr2 = np.array((
    [7,8,9],
    [10,11,12]
),dtype=np.float64)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [28]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [29]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [30]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [31]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [32]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [33]:
arr3 = 1 / arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [34]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[5]

5

In [37]:
arr[5:9]

array([5, 6, 7, 8])

In [38]:
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [39]:
arr[:5]

array([0, 1, 2, 3, 4])

In [40]:
arr[8:]

array([12,  9])

### 2차원 배열

In [42]:
arr2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],
])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
arr2d.dtype

dtype('int64')

In [44]:
# 2번 행의 자료 출력
arr2d[2,:]

array([ 9, 10, 11, 12])

In [56]:
# 1에서 2번행의 자료출력
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
# 3번 열의 자료 출력
arr2d[:,3]

array([ 4,  8, 12, 16])

In [58]:
# 0, 1열의 자료 출력
arr2d[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [54]:
# 1행 2열의 자료 출력
arr2d[1,2]

7

In [59]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
arr2d[:2,1:3] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
# 난수 발생
- rand : 0부터 1사이의 균일분포
- randn : 가우시안 표준 정규 분포
- randint : 균일 분포의 정수 난수

## Boolean Indexing

In [117]:
names = np.array(["Charles","Kenny","Hayoung","Charles","Hayoung","Kenny","Kenny"])
data = np.random.randn(7,4) 

In [118]:
names

array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny',
       'Kenny'], dtype='<U7')

In [119]:
names.shape

(7,)

In [120]:
data

array([[ 1.24098573,  2.29983148, -2.13834537,  0.4160051 ],
       [-0.07564047, -0.98955372,  0.55469282, -0.37765008],
       [ 1.9269568 , -1.50096341, -0.44505903, -0.49062581],
       [ 0.14119883, -0.48316936, -1.18918028, -1.67366458],
       [-0.26154324,  2.76497781, -0.32110575,  0.65893488],
       [-1.81417151,  0.04147595, -2.02209316,  1.53399103],
       [ 0.07831591, -0.39218063,  0.37998305, -0.11131854]])

In [121]:
data.shape

(7, 4)

In [122]:
# Mask
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [123]:
data[names == "Charles",:] # True에 해당하는 행 출력

array([[ 1.24098573,  2.29983148, -2.13834537,  0.4160051 ],
       [ 0.14119883, -0.48316936, -1.18918028, -1.67366458]])

In [124]:
data[(names == "Charles") | (names == "Kenny"),:]

array([[ 1.24098573,  2.29983148, -2.13834537,  0.4160051 ],
       [-0.07564047, -0.98955372,  0.55469282, -0.37765008],
       [ 0.14119883, -0.48316936, -1.18918028, -1.67366458],
       [-1.81417151,  0.04147595, -2.02209316,  1.53399103],
       [ 0.07831591, -0.39218063,  0.37998305, -0.11131854]])

In [125]:
data[:,3]

array([ 0.4160051 , -0.37765008, -0.49062581, -1.67366458,  0.65893488,
        1.53399103, -0.11131854])

In [126]:
# data의 4번째 열 값 중 0보다 작은 것의 mask만들기

data[:,3] < 0

array([False,  True,  True,  True, False, False,  True])

In [127]:
data[data[:,3] < 0,:]

array([[-0.07564047, -0.98955372,  0.55469282, -0.37765008],
       [ 1.9269568 , -1.50096341, -0.44505903, -0.49062581],
       [ 0.14119883, -0.48316936, -1.18918028, -1.67366458],
       [ 0.07831591, -0.39218063,  0.37998305, -0.11131854]])

In [128]:
# data의 4번째 열의 값이 0보다 작으면 data들을 0으로 대체하기

data[data[:,3] <0] = 0
data

array([[ 1.24098573,  2.29983148, -2.13834537,  0.4160051 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.26154324,  2.76497781, -0.32110575,  0.65893488],
       [-1.81417151,  0.04147595, -2.02209316,  1.53399103],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [129]:
# 정렬
arr = np.random.rand(8)
arr

array([0.64837483, 0.73264094, 0.45400631, 0.04957101, 0.34479122,
       0.31168223, 0.98502784, 0.65796194])

In [130]:
# 오름차순 정렬
np.sort(arr)

array([0.04957101, 0.31168223, 0.34479122, 0.45400631, 0.64837483,
       0.65796194, 0.73264094, 0.98502784])

In [131]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.98502784, 0.73264094, 0.65796194, 0.64837483, 0.45400631,
       0.34479122, 0.31168223, 0.04957101])

In [132]:
arr = np.random.rand(5,3)
arr

array([[0.94146714, 0.26935984, 0.11808474],
       [0.70099676, 0.19518256, 0.40618629],
       [0.16266305, 0.27204425, 0.93265112],
       [0.98205005, 0.68040039, 0.23660551],
       [0.73159824, 0.65416505, 0.49925867]])

In [133]:
np.sort(arr,axis=0) # 0 : 열방향 오름차순

array([[0.16266305, 0.19518256, 0.11808474],
       [0.70099676, 0.26935984, 0.23660551],
       [0.73159824, 0.27204425, 0.40618629],
       [0.94146714, 0.65416505, 0.49925867],
       [0.98205005, 0.68040039, 0.93265112]])

In [134]:
np.sort(arr,axis=1) # 1 : 행방향 오름차순

array([[0.11808474, 0.26935984, 0.94146714],
       [0.19518256, 0.40618629, 0.70099676],
       [0.16266305, 0.27204425, 0.93265112],
       [0.23660551, 0.68040039, 0.98205005],
       [0.49925867, 0.65416505, 0.73159824]])

In [135]:
np.sort(arr,axis=0)[::-1] # 0 : 열방향 내림차순

array([[0.98205005, 0.68040039, 0.93265112],
       [0.94146714, 0.65416505, 0.49925867],
       [0.73159824, 0.27204425, 0.40618629],
       [0.70099676, 0.26935984, 0.23660551],
       [0.16266305, 0.19518256, 0.11808474]])

In [137]:
# 중복제거
np.unique(names)

array(['Charles', 'Hayoung', 'Kenny'], dtype='<U7')

---
# reshape

In [139]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [140]:
arr.shape

(8,)

In [141]:
# 2차원 배열로 변경
arr1 = np.reshape(arr,(2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [143]:
# 3차원 배열로 변경
arr2 = np.reshape(arr,(2,2,2)) # (page,row,column)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [144]:
# 2차원 배열을 1차원으로 변경
arr3 = arr1.reshape(-1,1) # 데이터 개수를 정할 수 없는 경우 : -1 (행의 수를 알아서 지정)
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [151]:
# 3차원 배열을 1차원으로 변경 
arr4 = arr2.reshape(-1)# 딥러닝에서는 1을 꼭 표시해줘야한다. 
                       # (이미지 학습시킬 때) 1차원이라고 차원 수를 꼭 알려줘야한다
                       # 일반적으로 사용 , 딥러닝에서는 사용하지 못함 
# arr4 = arr2.reshape(-1 , 1) 
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [152]:
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])