In [54]:
import pandas as pd
data = pd.read_csv("../Data/gpascore.csv")
data.head()

admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

### Preprocessing(전처리)

In [55]:
# 결측치 처리
data.isnull().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [56]:
# 결측치 데이터 삭제
data.dropna(inplace=True)

# 결측치 데이터를 다른 값으로  대체
# data.fillna(100)

In [57]:
# 결측치 처리 후 확인 
data.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [58]:
# rank의 종류 파악 종류 파악 
sorted(data['rank'].unique())

[1, 2, 3, 4]

In [59]:
# 영어 점수의 최솟값과 최대값
print('최대값 :',data['gre'].max())
print('최소값 :',data['gre'].min())

최대값 : 800.0
최소값 : 220.0


In [60]:
# Training Data
x = data[['gre','gpa','rank']]
x.head()

gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [61]:
# target Data
y = data['admit']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [62]:
x.count()

gre     425
gpa     425
rank    425
dtype: int64

---
### Deep Learning Model 만들기

In [63]:
from tensorflow import keras

In [64]:
input_layer = keras.layers.InputLayer(input_shape=(3,))
hidden_layer = keras.layers.Dense(256,activation='tanh')
output_layer = keras.layers.Dense(1,activation='sigmoid')

In [65]:
model = keras.Sequential(
    [
        input_layer,
        hidden_layer,
        output_layer
    ]
)


In [66]:
# 손실함수
model.compile(optimizer='adam',loss='binary_crossentropy',metrics='accuracy')
# Optimize : learning rate를 알맞게 조정해줌
# - adam 
# - adagrad
# - adaelta
# - rmsprop
# - sgd
# loss : 손실함수
# -binary_crossentropy : 분류 및 확률 예측
# metrics : 모델의 평가 기준

In [67]:
# 학습 시키기
import numpy as np
model.fit(np.array(x),np.array(y),epochs=500)

Epoch 1/500
14/14 [==============================] - 0s 1ms/step - loss: 0.6838 - accuracy: 0.5506
Epoch 2/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6889 - accuracy: 0.5765
Epoch 3/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6770 - accuracy: 0.6306
Epoch 4/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6763 - accuracy: 0.5600
Epoch 5/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6720 - accuracy: 0.5812
Epoch 6/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6624 - accuracy: 0.6235
Epoch 7/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6726 - accuracy: 0.5365
Epoch 8/500
14/14 [==============================] - 0s 3ms/step - loss: 0.6775 - accuracy: 0.5788
Epoch 9/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6791 - accuracy: 0.5671
Epoch 10/500
14/14 [==============================] - 0s 3ms/step - loss: 0.6812 - accuracy: 0.5365
Epoch 11/

In [68]:
# hidden layer의 가중치 값 출력
hidden_layer.get_weights()[0] # input이 3개이므로 가중치도 3개씩 출력됨 

array([[ 9.82843637e-02,  3.51167060e-02,  8.96313637e-02,
         4.97310609e-02, -7.77934119e-02,  3.78511995e-02,
         7.71768391e-02, -3.57801951e-02, -1.27315342e-01,
        -5.02251685e-02, -1.04265928e-01, -5.86240813e-02,
         3.58833969e-02, -8.14650878e-02,  4.21351045e-02,
         9.73713547e-02,  6.89117163e-02,  7.49384016e-02,
        -9.07816216e-02, -1.33626521e-01, -1.31365508e-01,
        -4.96818200e-02,  1.19714260e-01,  1.45743698e-01,
        -1.48616686e-01, -1.41031608e-01,  3.65548655e-02,
         3.00495978e-03,  6.48293346e-02, -3.55298184e-02,
        -1.34816632e-01, -7.19940066e-02, -8.76336545e-02,
        -1.37569636e-01, -1.34969547e-01, -1.43939018e-01,
        -4.89934385e-02, -4.43043783e-02, -1.38967320e-01,
        -1.17214300e-01, -3.65192778e-02,  4.69798744e-02,
         5.14629930e-02,  1.32199274e-02,  1.65577121e-02,
        -2.68507916e-02,  7.23845810e-02, -4.28358316e-02,
        -5.49387187e-02,  1.47458285e-01,  9.79562104e-0

In [69]:
hidden_layer.get_weights()[1]

array([ 0.00000000e+00,  6.47178292e-03,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -3.50700226e-03,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  6.18453021e-04, -1.09451687e+00,
        0.00000000e+00, -2.23382696e-04,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -9.06130939e-04,  0.00000000e+00,  0.00000000e+00,  1.35823324e-01,
        1.06793396e-01, -4.20980677e-02,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

In [70]:
# hidden layer의 출력 확인하기
intermediate_layer_model = keras.Model(inputs=model.input,outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(np.array(x))

In [71]:
intermediate_output

<tf.Tensor: shape=(425, 256), dtype=float32, numpy=
array([[ 1.,  1.,  1., ...,  1., -1.,  1.],
       [ 1.,  1.,  1., ...,  1., -1.,  1.],
       [ 1.,  1.,  1., ...,  1., -1.,  1.],
       ...,
       [ 1.,  1.,  1., ...,  1., -1.,  1.],
       [ 1.,  1.,  1., ...,  1., -1.,  1.],
       [ 1.,  1.,  1., ...,  1., -1.,  1.]], dtype=float32)>